### PR TITLE
Start Revision Spanish transalation W2

### PR DESCRIPTION
**Pull request by rcpacheco**

### CODE REVIEW

**Comment by rcpacheco** [comment]
I added today the remaining revision for Spanish W2. It is complete now

**Comment by SergeStinckwich** [comment]
This PR is still valid ?

**Comment by estebanlm** [comment]
why not?
spanish translations seems correct (@rcpacheco formalised the translation, which is better).

**Comment by SergeStinckwich** [comment]
Because this PR and was never merged.

**Comment by SergeStinckwich** [comment]
Merged !

**Pull request merged**
