### PR TITLE
Create C019SD-Teaser-v4-JA.srt

### PR DESCRIPTION
**Pull request by tomooda**
Initial translation to the Japanese language

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Thank you Tomo !

**Comment by Ducasse** [comment]
Yes thanks you!

**Comment by tomooda** [comment]
Please tell me what I can do for the remaining materials at ESUG.

**Comment by Ducasse** [comment]
In fact it would be great if we could get more than the teaser. 
We have all the videos in french and they have subtitles in french and english and it would be great to have them in Japanes. We will have the voice in english this year. 

stef

**Pull request merged**
